// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: achievement_api.proto

package com.blemobi.sep.probuf;

public final class AchievementProtos {
  private AchievementProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PAchievementActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.PAchievementAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional int32 msgid = 2;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    int getMsgid();

    /**
     * <code>optional int32 value = 3;</code>
     *
     * <pre>
     * 整数类型的值，如好友数、加入的社区数
     * </pre>
     */
    int getValue();

    /**
     * <code>optional bytes extra = 4;</code>
     *
     * <pre>
     * 额外的数据，根据msgid不同而不同
     * </pre>
     */
    com.google.protobuf.ByteString getExtra();
  }
  /**
   * Protobuf type {@code service.PAchievementAction}
   *
   * <pre>
   * 来自各个服务的消息
   * </pre>
   */
  public  static final class PAchievementAction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.PAchievementAction)
      PAchievementActionOrBuilder {
    // Use PAchievementAction.newBuilder() to construct.
    private PAchievementAction(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PAchievementAction() {
      uuid_ = "";
      msgid_ = 0;
      value_ = 0;
      extra_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PAchievementAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              uuid_ = bs;
              break;
            }
            case 16: {

              msgid_ = input.readInt32();
              break;
            }
            case 24: {

              value_ = input.readInt32();
              break;
            }
            case 34: {

              extra_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.class, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private int msgid_;
    /**
     * <code>optional int32 msgid = 2;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public int getMsgid() {
      return msgid_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private int value_;
    /**
     * <code>optional int32 value = 3;</code>
     *
     * <pre>
     * 整数类型的值，如好友数、加入的社区数
     * </pre>
     */
    public int getValue() {
      return value_;
    }

    public static final int EXTRA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString extra_;
    /**
     * <code>optional bytes extra = 4;</code>
     *
     * <pre>
     * 额外的数据，根据msgid不同而不同
     * </pre>
     */
    public com.google.protobuf.ByteString getExtra() {
      return extra_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        output.writeBytes(1, getUuidBytes());
      }
      if (msgid_ != 0) {
        output.writeInt32(2, msgid_);
      }
      if (value_ != 0) {
        output.writeInt32(3, value_);
      }
      if (!extra_.isEmpty()) {
        output.writeBytes(4, extra_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (msgid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgid_);
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, value_);
      }
      if (!extra_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, extra_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.AchievementProtos.PAchievementAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.PAchievementAction}
     *
     * <pre>
     * 来自各个服务的消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.PAchievementAction)
        com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.class, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        msgid_ = 0;

        value_ = 0;

        extra_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementAction_descriptor;
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction build() {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction buildPartial() {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementAction result = new com.blemobi.sep.probuf.AchievementProtos.PAchievementAction(this);
        result.uuid_ = uuid_;
        result.msgid_ = msgid_;
        result.value_ = value_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.AchievementProtos.PAchievementAction) {
          return mergeFrom((com.blemobi.sep.probuf.AchievementProtos.PAchievementAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.AchievementProtos.PAchievementAction other) {
        if (other == com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getMsgid() != 0) {
          setMsgid(other.getMsgid());
        }
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (other.getExtra() != com.google.protobuf.ByteString.EMPTY) {
          setExtra(other.getExtra());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.AchievementProtos.PAchievementAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }

      private int msgid_ ;
      /**
       * <code>optional int32 msgid = 2;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public int getMsgid() {
        return msgid_;
      }
      /**
       * <code>optional int32 msgid = 2;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public Builder setMsgid(int value) {
        
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgid = 2;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public Builder clearMsgid() {
        
        msgid_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>optional int32 value = 3;</code>
       *
       * <pre>
       * 整数类型的值，如好友数、加入的社区数
       * </pre>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 3;</code>
       *
       * <pre>
       * 整数类型的值，如好友数、加入的社区数
       * </pre>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 3;</code>
       *
       * <pre>
       * 整数类型的值，如好友数、加入的社区数
       * </pre>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes extra = 4;</code>
       *
       * <pre>
       * 额外的数据，根据msgid不同而不同
       * </pre>
       */
      public com.google.protobuf.ByteString getExtra() {
        return extra_;
      }
      /**
       * <code>optional bytes extra = 4;</code>
       *
       * <pre>
       * 额外的数据，根据msgid不同而不同
       * </pre>
       */
      public Builder setExtra(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes extra = 4;</code>
       *
       * <pre>
       * 额外的数据，根据msgid不同而不同
       * </pre>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:service.PAchievementAction)
    }

    // @@protoc_insertion_point(class_scope:service.PAchievementAction)
    private static final com.blemobi.sep.probuf.AchievementProtos.PAchievementAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.AchievementProtos.PAchievementAction();
    }

    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PAchievementAction> PARSER =
        new com.google.protobuf.AbstractParser<PAchievementAction>() {
      public PAchievementAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PAchievementAction(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PAchievementAction> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PAchievementActionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.PAchievementActions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> 
        getArrayList();
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getArray(int index);
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    int getArrayCount();
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    java.util.List<? extends com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder> 
        getArrayOrBuilderList();
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder getArrayOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code service.PAchievementActions}
   *
   * <pre>
   * 消息数组
   * </pre>
   */
  public  static final class PAchievementActions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.PAchievementActions)
      PAchievementActionsOrBuilder {
    // Use PAchievementActions.newBuilder() to construct.
    private PAchievementActions(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PAchievementActions() {
      array_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PAchievementActions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                array_ = new java.util.ArrayList<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction>();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.add(input.readMessage(com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = java.util.Collections.unmodifiableList(array_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementActions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementActions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.class, com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.Builder.class);
    }

    public static final int ARRAY_FIELD_NUMBER = 1;
    private java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> array_;
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    public java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> getArrayList() {
      return array_;
    }
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    public java.util.List<? extends com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder> 
        getArrayOrBuilderList() {
      return array_;
    }
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getArray(int index) {
      return array_.get(index);
    }
    /**
     * <code>repeated .service.PAchievementAction array = 1;</code>
     */
    public com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder getArrayOrBuilder(
        int index) {
      return array_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < array_.size(); i++) {
        output.writeMessage(1, array_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < array_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, array_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.AchievementProtos.PAchievementActions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.PAchievementActions}
     *
     * <pre>
     * 消息数组
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.PAchievementActions)
        com.blemobi.sep.probuf.AchievementProtos.PAchievementActionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementActions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementActions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.class, com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArrayFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrayBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.AchievementProtos.internal_static_service_PAchievementActions_descriptor;
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementActions getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementActions build() {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementActions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.AchievementProtos.PAchievementActions buildPartial() {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementActions result = new com.blemobi.sep.probuf.AchievementProtos.PAchievementActions(this);
        int from_bitField0_ = bitField0_;
        if (arrayBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            array_ = java.util.Collections.unmodifiableList(array_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.array_ = array_;
        } else {
          result.array_ = arrayBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.AchievementProtos.PAchievementActions) {
          return mergeFrom((com.blemobi.sep.probuf.AchievementProtos.PAchievementActions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.AchievementProtos.PAchievementActions other) {
        if (other == com.blemobi.sep.probuf.AchievementProtos.PAchievementActions.getDefaultInstance()) return this;
        if (arrayBuilder_ == null) {
          if (!other.array_.isEmpty()) {
            if (array_.isEmpty()) {
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrayIsMutable();
              array_.addAll(other.array_);
            }
            onChanged();
          }
        } else {
          if (!other.array_.isEmpty()) {
            if (arrayBuilder_.isEmpty()) {
              arrayBuilder_.dispose();
              arrayBuilder_ = null;
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrayBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArrayFieldBuilder() : null;
            } else {
              arrayBuilder_.addAllMessages(other.array_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.AchievementProtos.PAchievementActions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.AchievementProtos.PAchievementActions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> array_ =
        java.util.Collections.emptyList();
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          array_ = new java.util.ArrayList<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction>(array_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.blemobi.sep.probuf.AchievementProtos.PAchievementAction, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder, com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder> arrayBuilder_;

      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> getArrayList() {
        if (arrayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(array_);
        } else {
          return arrayBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public int getArrayCount() {
        if (arrayBuilder_ == null) {
          return array_.size();
        } else {
          return arrayBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction getArray(int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);
        } else {
          return arrayBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder setArray(
          int index, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.set(index, value);
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder setArray(
          int index, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder addArray(com.blemobi.sep.probuf.AchievementProtos.PAchievementAction value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder addArray(
          int index, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(index, value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder addArray(
          com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder addArray(
          int index, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder addAllArray(
          java.lang.Iterable<? extends com.blemobi.sep.probuf.AchievementProtos.PAchievementAction> values) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, array_);
          onChanged();
        } else {
          arrayBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder clearArray() {
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public Builder removeArray(int index) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.remove(index);
          onChanged();
        } else {
          arrayBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder getArrayBuilder(
          int index) {
        return getArrayFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder getArrayOrBuilder(
          int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);  } else {
          return arrayBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public java.util.List<? extends com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder> 
           getArrayOrBuilderList() {
        if (arrayBuilder_ != null) {
          return arrayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(array_);
        }
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder addArrayBuilder() {
        return getArrayFieldBuilder().addBuilder(
            com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.getDefaultInstance());
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder addArrayBuilder(
          int index) {
        return getArrayFieldBuilder().addBuilder(
            index, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.getDefaultInstance());
      }
      /**
       * <code>repeated .service.PAchievementAction array = 1;</code>
       */
      public java.util.List<com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder> 
           getArrayBuilderList() {
        return getArrayFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.blemobi.sep.probuf.AchievementProtos.PAchievementAction, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder, com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder> 
          getArrayFieldBuilder() {
        if (arrayBuilder_ == null) {
          arrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.blemobi.sep.probuf.AchievementProtos.PAchievementAction, com.blemobi.sep.probuf.AchievementProtos.PAchievementAction.Builder, com.blemobi.sep.probuf.AchievementProtos.PAchievementActionOrBuilder>(
                  array_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          array_ = null;
        }
        return arrayBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:service.PAchievementActions)
    }

    // @@protoc_insertion_point(class_scope:service.PAchievementActions)
    private static final com.blemobi.sep.probuf.AchievementProtos.PAchievementActions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.AchievementProtos.PAchievementActions();
    }

    public static com.blemobi.sep.probuf.AchievementProtos.PAchievementActions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PAchievementActions> PARSER =
        new com.google.protobuf.AbstractParser<PAchievementActions>() {
      public PAchievementActions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PAchievementActions(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PAchievementActions> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.AchievementProtos.PAchievementActions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_PAchievementAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_PAchievementAction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_PAchievementActions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_PAchievementActions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025achievement_api.proto\022\007service\"O\n\022PAch" +
      "ievementAction\022\014\n\004uuid\030\001 \001(\t\022\r\n\005msgid\030\002 " +
      "\001(\005\022\r\n\005value\030\003 \001(\005\022\r\n\005extra\030\004 \001(\014\"A\n\023PAc" +
      "hievementActions\022*\n\005array\030\001 \003(\0132\033.servic" +
      "e.PAchievementActionB+\n\026com.blemobi.sep." +
      "probufB\021AchievementProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service_PAchievementAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service_PAchievementAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_PAchievementAction_descriptor,
        new java.lang.String[] { "Uuid", "Msgid", "Value", "Extra", });
    internal_static_service_PAchievementActions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service_PAchievementActions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_PAchievementActions_descriptor,
        new java.lang.String[] { "Array", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
